set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports clk_i]

set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33} [get_ports rst]

set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports led_ca]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports led_cb]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports led_cc]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports led_cd]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports led_ce]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports led_cf]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports led_cg]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS33} [get_ports led_dp]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports led7_en]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports led6_en]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports led5_en]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports led4_en]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33} [get_ports led3_en]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports led2_en]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33} [get_ports led1_en]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS33} [get_ports led0_en]
